### PR TITLE
UAF-5480 : Copying a 3.0 Cash Receipt Bursar Rep unable to approve doc

### PR DESCRIPTION
**Pull request by amandazhangm**
KFS 5.0 delivered 4.1.1_5.0/db/01_structure/fp-module-structure-updates.xml  with change set ID = KFS_50_FP_DEPOSIT_HDR_T to convert data for DB FP_CHECK_DTL_T replace DOC_COLUMN_TYP_CD	column by CSHR_STAT_CD. Per vanilla, "It uses the existing value in that field to set the new CSHR_STAT_CD value *if* the FDOC_TYP_CD on the record is “CR” or “CM”. Existing value of FDOC_COLUMN_TYP_CD may have 'C' for checks or 'R' for confirmed checks. " However, UA runs 3.0 in PROD which does not have 'C' checks value in FDOC_COLUMN_TYP_CD  column. Only 'R' exists to represent checks/confirmed checks. 

The solution is to develop data conversion script for UA KFS3.0 data to accommodate this DB change. This DB conversion script include two steps,

1. Convert 'C' check type for all entries in FP_CHECK_DTL_T regardless CR document routing status. In KFS 5.0+, only check ('C' type) when submit CR. 
2. Creating new 'R' confirmed check entries in FP_CHECK_DTL_T by duplicating 'C' check entry from the same CR.	Creating new 'R' confirmed checks for CR if it's Final or Processed, 'A' or 'V' in FS_DOC_HEADER_T. In KFS5.0+, confirmed check('R' check) is required to approve CR to final.

### CODE REVIEW

**Comment by Perrinek** [comment]
I'm curious as to why step 2 requires an insert. As we are only changing the status of the check detail record, why is this not an update?

**Comment by amandazhangm** [comment]
Check details and confirmed checks are two different check types in KFS5. 0 which are handled by step 1 ( update check type to 'C' ) and step 2 (create new entries for check type 'R' - confirmed) respectively. In KFS3, it only has check details which is represented by 'R' in  DOC_COLUMN_TYP_CD, i.e. it looks have checks and confirmed checks combined in kfs5 without conversion, however, KFS5 those two types should be separated that check details are entered by initiator ('C' type) vs. Confirmed checks('R' type) are created by cash manager approvers. Since only one type of check entry in kfs3, we need to create new type (confirmed check - 'R') in the same table.

**Comment by Perrinek** [comment]
It still doesn't make sense to me that we could have 2 check detail records on a CR document that are exactly alike, except one has a cashiering status of 'C' and the other has a cashiering status of 'R'. But, I'll take your word for it that this is required. Merging.

**Comment by Perrinek** [comment]
Wait, I think your new sql file name (sql/UAF-5480_data_conv_FP_CHECK_DTL_T.sql), needs to be added to property files-post-upgrade in file src/main/resources/kfsdbupgrade.properties.

**Comment by Perrinek** [comment]
Looks good!

**Comment by amandazhangm** [comment]
Good catch, Julie. Updated files-post-upgrade property with new sql file appended at the end.  This change has been committed. 
Regarding two entries for each check except check type 'C' vs. 'R' since 'C' represent check entered by initiator. 'R' was 'entered' by Cash Manager approver who can simply click 'copyAllChecks' to generate confirmed checks ('R') by copying 'C' check. Though Cash Manger may modify confirmed check by enter confirmed check details in kfs6 which can make checks and confirmed checks look different, however, kfs3 cash manager can't modify check details, i.e. if projecting kfs3 check details in kfs6, confirmed check equal to check details.

**Pull request merged**
