### PR TITLE
UAF-2787: Added exception logging to MaintainableXMLConversionServiceImpl.java; Finished Endowment updates removes

### PR DESCRIPTION
**Pull request by jreeseUA**
UAF-2787: Added exception logging with variable details to MaintainableXMLConversionServiceImpl.java; UAF-2544 Completed Endowment-Addendum Updates and removals and Endowment removals

### CODE REVIEW

**Comment by jreeseUA** [comment]
Good point. My intention was to capture both the very specific segment of XML data that caused the failure, to aid in correcting it, and the encapsulating segment containing the problem segment, to aid in finding it. Admittedly, there are cleaner ways to achieve both. I'll rework it and probably err to the side of capturing the detail at the low level since we have the macro document data already and yet haven't found the problem elements.  Also this minimizes the potential logging of sensitive info you noted. Thank you.

**Comment by jreeseUA** [comment]
Modified code to use the recommended wrap and re-throw exception pattern.

**Comment by Perrinek** [comment]
OK, I thought this PR was strictly for Jira UAF-2544, which is why I volunteered to do the peer review. I didn't realize that a peer review was already in process. This should be two separate PRs, one for each Jira. Please do not include the work for more than one Jira in one PR unless the work for the second Jira is extremely limited in scope. Should I review the code for Jira UAF-2544 or has that already been done?

**Comment by Perrinek** [comment]
BTW, this PR has merge conflicts that need to be resolved before peer review can continue.

**Pull request closed without merging**
