### PR TITLE
UAF-5231 : KFS7 STG Roles Will Not Load

### PR DESCRIPTION
**Pull request by amandazhangm**
Description of issue: role_id=1305 can't load for edit due to can't retrieve role type service. Role type service for role_id=1305 is derived role type service which should be published by KFS. To retrieve derived role type service published by KFS, it needs to be declared as KSB published service name.
Fix: to update KRIM_TYP_T for kim_typ_id = '1102' to use KSB published service name.

### CODE REVIEW

**Comment by nataliac06** [comment]
Waiting to merge till after release is built

**Comment by Perrinek** [comment]
This change seems to be a reversal of the first changeset in the following Liquibase changelog (originated with KFS 6 upgrade): https://github.com/ua-eas/financials/blob/ua-development/kfs-core/src/main/resources/edu/arizona/kfs/db/changelog/changesets/db.changelog-UAF-2042.xml

Should we remove the Liquibase?

**Comment by amandazhangm** [comment]
I noticed about file db.changelog-UAF-2042.xml that updated KIM_TYP_ID = '1102'. I didn't go to the route to reverse it initially since I was not sure about 1) which Jenkins job that picked it up and applied to DB? 2) if the value before it being applied is the expected the same value that we'll need. I adopted incremental DB change strategy to apply another script on top of what have been applied.  If reversing is preferred, I can try that approach.

**Comment by amandazhangm** [comment]
Thank you for reviewing, Natalia. By saying 'KFS7 liquibase will be applied on top of it so the effect will be annulled', do you mean https://github.com/ua-eas/financials/blob/ua-development/kfs-core/src/main/resources/edu/arizona/kfs/db/changelog/changesets/db.changelog-UAF-2042.xml will apply as part of KFS7 dbupgrade steps? I may need to learn more details about Jenkins upgrade steps. Please direct me to the Jenkin job that runs db.changelog-UAF-2042.xml. Thank you.

**Comment by nataliac06** [comment]
Yes, that's correct. The kfsdbupgrade project is for upgrading from 3 to 6 and all the .sql scripts in there will be applied before any liquibase is ran. Then the other project, to upgrade from 6 to 7 will run, then all the KFS7 liquibase scripts in the financials will run.
See documentation about Jenkins jobs here: https://confluence.arizona.edu/display/KFS5Up/UAF+Database+Upgrade+in+AWS

**Comment by amandazhangm** [comment]
Hi Natalia, the DB upgrade link is very helpful. With tracing the listed DB steps, it looks the liquibase file(db.changelog-UAF-2042.xml) that needs to reverse only runs from UA liquibase set which runs by upgrading from 3 to 6 -  "UAF 3 to 6 DB Upgrade - nonprod - 4 - Execute Released UA Liquibase". From KFS 6 to 7, only vanilla/KualiCo LiquiBase change set will run. Please correct me if this is not right.

I'll revert the change db.changelog-UAF-2042.xml. Since reverting only applies to kfs7 code branches, it won't affect/break kfs6 db build. I'll close current PR and apply change to financials instead.

**Pull request closed without merging**
